# AUTO-GENERATED by the strategy authoring compiler. Safe to edit, but re-installing
# from the spec will overwrite. is_builtin=False marks this a custom plugin.
from __future__ import annotations
import pandas as pd
from app.strategies.base import StrategyBase, Signal


class AlgotestOptionBuyNifty(StrategyBase):
    id = 'algotest_option_buy_nifty'
    name = 'NF_CE_PE_EXP2_Base'
    version = '1.0.0'
    description = 'Intraday momentum breakout strategy with contingent lazy legs triggered upon primary leg stop-loss hits.'
    is_builtin = False
    supported_instruments = ['NIFTY', 'BANKNIFTY', 'SENSEX']
    supported_modes = ['SCALP', 'INTRADAY']
    supported_timeframes = ['1m', '3m', '5m']
    # Bounds/pins regenerated 2026-07-29 by `compiler.premium_param_schema_entry`
    # after the optimizer was found tuning `lots` to 100 (the invented [0,100]
    # ceiling) and inflating reported P&L 50x. `fixed` = declared, honoured, but
    # NOT a search dimension; min/max are derived from the shipped
    # premium_momentum plugin's curated ranges.
    parameter_schema = {
        'reference_time': {"type": 'str', "default": '09:31'},
        'moneyness': {"type": 'str', "default": 'itm1'},
        'side': {"type": 'str', "default": 'first_to_trigger'},
        'leg_mode': {"type": 'str', "default": 'both'},
        'momentum_pct': {"type": 'int', "min": 5, "max": 50, "default": 15},
        'stop_pct': {"type": 'int', "min": 10, "max": 40, "default": 20},
        'target_pct': {"type": 'int', "fixed": 50, "default": 50},
        'trail_x_pct': {"type": 'int', "fixed": 5, "default": 5},
        'trail_y_pct': {"type": 'int', "fixed": 5, "default": 5},
        'lots': {"type": 'int', "fixed": 2, "default": 2},
        'entry_cutoff': {"type": 'str', "default": '15:09'},
        'exit_time': {"type": 'str', "default": '15:13'},
        'lazy_enabled': {"type": 'bool', "default": True},
        'lazy_moneyness': {"type": 'str', "default": 'itm1'},
        'lazy_momentum_pct': {"type": 'int', "min": 5, "max": 50, "default": 10},
        'lazy_stop_pct': {"type": 'int', "min": 10, "max": 40, "default": 10},
        'lazy_target_pct': {"type": 'int', "fixed": 50, "default": 50},
        'lazy_trail_x_pct': {"type": 'int', "fixed": 5, "default": 5},
        'lazy_trail_y_pct': {"type": 'int', "fixed": 5, "default": 5},
    }

    def evaluate(self, row: pd.Series, prev: pd.Series, params, ctx) -> Signal:
        """Inert by design: this strategy is premium-native, so the premium
        session engine (Track B) decides entries and this method is never
        called. Do NOT 'fix' it into a real evaluate — that would create a
        second, silently-ignored decision path."""
        return Signal(direction="NONE", blockers=["premium-native: driven by the premium session engine"])
